/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pierre' at '28/04/17 14:44' with Gradle 2.14.1
 *
 * @author pierre, @date 28/04/17 14:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
